version: "3.8"

services:
  app:
    container_name: PyForgeApp
    build: ./services
    volumes:
      - ./services/:/home/app
    env_file:
      - .env.dev
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=compounds_db

volumes:
  postgres_data: